# Generated by Django 3.0.3 on 2020-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_Name', models.CharField(max_length=200)),
                ('createDate', models.DateTimeField(verbose_name='建立日期')),
                ('modifyDate', models.DateTimeField(verbose_name='修改日期')),
            ],
        ),
    ]
