# Generated by Django 3.0.3 on 2020-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_Name',
        ),
        migrations.AddField(
            model_name='part',
            name='partName',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='partTxt',
            field=models.CharField(default='部位', max_length=10),
        ),
    ]
