# Generated by Django 3.0.3 on 2020-03-09 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20200306_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 15, 52, 49, 21794), verbose_name='建立日期'),
        ),
        migrations.AlterField(
            model_name='part',
            name='modify_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 15, 52, 49, 21794), verbose_name='修改日期'),
        ),
    ]
