# Generated by Django 3.0.3 on 2020-03-09 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_auto_20200309_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateTimeField(default=datetime.datetime(2020, 3, 9, 15, 53, 9, 731290), verbose_name='記錄日期')),
                ('repes', models.IntegerField(verbose_name='次數')),
                ('sets', models.IntegerField(verbose_name='組數')),
                ('actionItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.ActionItem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weigth', models.FloatField(verbose_name='重量')),
                ('repes', models.IntegerField(null=True, verbose_name='次數')),
                ('remark', models.CharField(max_length=20, verbose_name='備註')),
                ('dailyItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailyrecords.DailyItem')),
            ],
        ),
    ]
