# Generated by Django 3.0.3 on 2020-03-09 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0007_auto_20200309_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, null=True)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 3, 9, 15, 52, 49, 57671), verbose_name='建立日期')),
                ('modify_date', models.DateTimeField(default=datetime.datetime(2020, 3, 9, 15, 52, 49, 57671), verbose_name='修改日期')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.Part')),
            ],
        ),
    ]
