# Generated by Django 3.0.3 on 2020-03-26 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200309_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 10, 37, 35, 204741), verbose_name='建立日期'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='modify_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 10, 37, 35, 204741), verbose_name='修改日期'),
        ),
    ]
